services:
  orthanc:
    image: orthancteam/orthanc
    ports:
      - 8042:8042
      - 4242:4242
    volumes:
      - ./orthanc-config/orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./orthanc-storage:/var/lib/orthanc/db
